# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Ryan Grier'
tagline:             ''
description:         'A site where I write (poorly) about a lot of dumb stuff.'
url:                 https://ryan.grier.co
baseurl:             ''
paginate:            5
plugins:             [jekyll-paginate, jekyll-feed]

# About/contact
author:
  name:              Ryan Grier
  url:               https://ryan.grier.co
  twitter:           rwgrier

# Custom vars
version:             1.1.3
lanyon-version:      1.1.0
